{
 "title": ".*#service_name#.*: General Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "resource_data", "query": "prometheus" },
   { "name": "env", "query": "test,uat,live" },
   { "name": "cid", "query": "id,sg,br,xx" },
   {
    "name": "tenant",
    "query": "id,sg,vn,my,ph,th,tw,br,mx,xx,ID"
   }
  ]
 },
 "panels": [
  {
   "title": "Container Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(kube_pod_status_ready{pod=~\".*#service_name#.*-[a-z]+-$env-$cid.*\"}, \"pod_group\", \"$1\", \"pod\", \"(.*#service_name#.*-[a-z]+-$env-$cid).*\")) by (pod_group)",
     "legendFormat": "{{pod_group}}"
    }
   ]
  },
  {
   "title": "Max instance CPU（top 400%）",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(increase(process_cpu_seconds_total{service=~\".*#service_name#.*\",env=\"$env\",cid=~\"$cid\"}[60s]) / 60)"
    }
   ]
  },
  {
   "title": "Max instance memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(go_memstats_sys_bytes{env=\"$env\",service=~\".*#service_name#.*\",cid=~\"$cid\"})"
    }
   ]
  },
  {
   "title": "Max instance Goroutines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(go_goroutines{env=\"$env\",service=~\".*#service_name#.*\",cid=~\"$cid\"})"
    }
   ]
  },
  {
   "title": "Min QPS ",
   "type": "stat",
   "description": "Min RPS in the last 60 seconds",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(increase(idgame_handled_total{service=~\".*#service_name#.*\", env=~\"$env\", path!~\".*ping.*\", region!=\"xx\"}[1m]))"
    }
   ]
  },
  {
   "title": "Current Total QPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(idgame_handled_total{service=~\".*#service_name#.*\",env=~\"$env\", path!~\".*ping.*\", region!=\"xx\"}[1m])) "
    }
   ]
  },
  {
   "title": "Max QPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum(rate(idgame_handled_total{service=~\".*#service_name#.*\",env=\"$env\",region!=\"xx\"}[1m]))[1h:1m])"
    }
   ]
  },
  {
   "title": "Total Request (Time Range)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(idgame_handled_total{service=~\".*#service_name#.*\", env=~\"$env\", path!~\".*ping.*\", region!=\"xx\"}[$__range]))"
    }
   ]
  },
  {
   "title": "p99 delay",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(idgame_handled_seconds_bucket{service=~\".*#service_name#.*\",env=~\"$env\",cid=~\"$cid\", path!~\".*ping.*\", region!=\"xx\"}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "HTTP Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(increase(idgame_handled_total{service=~\".*#service_name#.*\",env=~\"$env\", cid=~\"$cid\", tenant=~\"id|sg|br\", status_code=~\"4.*|5.*\"}[1m]))",
     "legendFormat": "Error count"
    },
    {
     "expr": "sum(increase(idgame_handled_total{service=~\".*#service_name#.*\",env=~\"$env\", cid=~\"$cid\", tenant=~\"$tenant\", status_code=~\"3.*|2.*\"}[1m]))  / sum(increase(idgame_handled_total{service=~\".*#service_name#.*\",env=~\"$env\", cid=~\"$cid\", tenant=~\"$tenant\"}[1m])) * 100\n",
     "legendFormat": "Success rate (%)"
    },
    {
     "expr": "sum(increase(idgame_handled_total{service=~\".*#service_name#.*\",env=~\"$env\", cid=~\"$cid\", tenant=~\"$tenant\", status_code=~\"4.*|5.*\"}[1m]))  / sum(increase(idgame_handled_total{service=~\".*#service_name#.*\",env=~\"$env\", cid=~\"$cid\", tenant=~\"$tenant\"}[1m])) * 100",
     "legendFormat": "Error rate (%)"
    }
   ]
  },
  {
   "title": "HTTP Total Request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "sum(increase(idgame_handled_total{service=~\".*#service_name#.*\",env=~\"$env\", cid=~\"$cid\", tenant=~\"$tenant\"}[1m]))",
     "legendFormat": "Total request"
    }
   ]
  },
  { "title": "Traffic Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "HTTP Request Count [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(increase(idgame_handled_total{service=~\".*#service_name#.*\",env=~\"$env\", cid=~\"$cid\", tenant=~\"$tenant\", path!~\".*ping.*\", region!=\"xx\"}[1m])) by(path, method)",
     "legendFormat": "{{path}}-{{method}}"
    }
   ]
  },
  {
   "title": "HTTP latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(increase(idgame_handled_seconds_sum{service=~\".*#service_name#.*\",env=~\"$env\", cid=~\"$cid\", tenant=~\"$tenant\", path!~\".*ping.*\", region!=\"xx\"}[1m]))by(path, method)/sum(increase(idgame_handled_seconds_count{service=~\".*#service_name#.*\",env=~\"$env\", cid=~\"$cid\", tenant=~\"$tenant\", path!~\".*ping.*\", region!=\"xx\"}[1m]))by(path, method)",
     "legendFormat": "{{path}}-{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Status Code [1M]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(idgame_handled_total{service=~\".*#service_name#.*\",env=~\"$env\", cid=~\"$cid\", tenant=~\"$tenant\", status_code!~\"200\", path!~\".*ping.*\", region!=\"xx\"}[1m])) by(path, method, status_code)",
     "legendFormat": "{{path}}-{{method}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "HTTP latency Pxx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(increase(idgame_handled_seconds_bucket{service=~\".*#service_name#.*\",env=~\"$env\", cid=~\"$cid\", tenant=~\"$tenant\", path!~\".*ping.*\", region!=\"xx\"}[1m])) by (le, path, method))",
     "legendFormat": "p95: {{path}}-{{method}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum(increase(idgame_handled_seconds_bucket{service=~\".*#service_name#.*\",env=~\"$env\", cid=~\"$cid\", tenant=~\"$tenant\", path!~\".*ping.*\", region!=\"xx\"}[1m])) by (le, path, method))",
     "legendFormat": "p75: {{path}}-{{method}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(increase(idgame_handled_seconds_bucket{service=~\".*#service_name#.*\",env=~\"$env\", cid=~\"$cid\", tenant=~\"$tenant\", path!~\".*ping.*\", region!=\"xx\"}[1m])) by (le, path, method))",
     "legendFormat": "p50: {{path}}-{{method}}"
    }
   ]
  },
  { "title": "Resource Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(rate(container_cpu_usage_seconds_total{pod=~\".*#service_name#.*\", image!~\".*pause.*\", pod!~\".*-xx.*\"}[60s]) / max(kube_pod_container_resource_limits_cpu_cores{pod=~\".*#service_name#.*\", pod!~\".*-xx-.*\"}) * 100)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(pod:pod_memory_usage:rate{pod_name=~\".*#service_name#.*\", pod_name!~\".*-xx.*\"} / (pod:pod_memory_limit_bytes{pod_name=~\".*#service_name#.*\", pod_name!~\".*-xx-.*\"} / 1024 / 1024 / 1024)) * 100",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod Restart Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{pod=~\".*#service_name#.*\", pod!~\".*-xx.*\"}[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory RSS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\".*#service_name#.*\", pod!~\".*-xx.*\", pod!~\".*\"} ) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{pod=~\".*#service_name#.*\", pod!~\".*-xx.*\", pod!~\".*\"}) by (pod) * 100",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kube_pod_status_ready{pod=~\".*#service_name#.*\", condition=\"true\", pod!~\".*-xx-.*\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Custom Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "MYSQL Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(increase(id_game_.*#service_name#.*_be_db_latency_sum{env=~\"$env\"}[1m])) by (query) / sum(increase(id_game_.*#service_name#.*_be_db_latency_count{env=~\"$env\"}[1m])) by (query)",
       "legendFormat": "{{key}}"
      }
     ]
    },
    {
     "title": "MYSQL Latency Pxx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(increase(id_game_.*#service_name#.*_be_db_latency_bucket{env=~\"$env\"}[1m])) by (le, query))",
       "legendFormat": "p95: {{query}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum(increase(id_game_.*#service_name#.*_be_db_latency_bucket{env=~\"$env\"}[1m])) by (le, query))",
       "legendFormat": "p75: {{query}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(increase(id_game_.*#service_name#.*_be_db_latency_bucket{env=~\"$env\"}[1m])) by (le, query))",
       "legendFormat": "p50: {{query}}"
      }
     ]
    },
    {
     "title": "Redis Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(increase(id_game_.*#service_name#.*_be_cache_latency_sum{env=~\"$env\"}[1m]))by(key)/sum(increase(id_game_.*#service_name#.*_be_cache_latency_count{env=~\"$env\"}[1m]))by(key)",
       "legendFormat": "{{key}}"
      }
     ]
    },
    {
     "title": "Redis Latency Pxx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(increase(id_game_.*#service_name#.*_be_cache_latency_bucket{env=~\"$env\"}[1m])) by (le, key))",
       "legendFormat": "p95: {{key}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum(increase(id_game_.*#service_name#.*_be_cache_latency_bucket{env=~\"$env\"}[1m])) by (le, key))",
       "legendFormat": "p75: {{key}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(increase(id_game_.*#service_name#.*_cache_latency_bucket{env=~\"$env\"}[1m])) by (le, key))",
       "legendFormat": "p50: {{key}}"
      }
     ]
    },
    {
     "title": "Redis Hit Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum(increase(id_game_.*#service_name#.*_be_cache_access{env=~\"$env\", is_hit=\"1\"}[1m])) by(key) / sum(increase(id_game_.*#service_name#.*_be_cache_access{env=~\"$env\"}[1m])) by(key)) * 100 ",
       "legendFormat": "{{key}}"
      }
     ]
    },
    {
     "title": "Consumer Process Status Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(id_game_.*#service_name#.*_be_consumer_process_status{env=~\"$env\", status=\"0\"}[1m])) by(topic, group_id)",
       "legendFormat": "Success - {{topic}} - {{group_id}}"
      },
      {
       "expr": "sum(increase(id_game_.*#service_name#.*_be_consumer_process_status{env=~\"$env\", status=\"1\"}[1m])) by(topic, group_id)",
       "legendFormat": "Error - {{topic}} - {{group_id}}"
      }
     ]
    },
    {
     "title": "External Service Latency Pxx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(increase(id_game_.*#service_name#.*_be_external_service_latency_bucket{env=~\"$env\"}[1m])) by (le, external_service, command))",
       "legendFormat": "p95: {{external_service}} - {{command}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum(increase(id_game_.*#service_name#.*_be_external_service_latency_bucket{env=~\"$env\"}[1m])) by (le, external_service, command))",
       "legendFormat": "p75: {{external_service}} - {{command}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(increase(id_game_.*#service_name#.*_be_external_service_latency_bucket{env=~\"$env\"}[1m])) by (le, external_service, command))",
       "legendFormat": "p50: {{external_service}} - {{command}}"
      }
     ]
    },
    {
     "title": "External Service Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(increase(id_game_.*#service_name#.*_be_external_service_latency_sum{env=~\"$env\"}[1m]))by(external_service, command)/sum(increase(id_game_.*#service_name#.*_be_external_service_latency_count{env=~\"$env\"}[1m]))by(external_service, command)",
       "legendFormat": "{{external_service}} - {{command}}"
      }
     ]
    },
    {
     "title": "External Service Error Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(id_game_.*#service_name#.*_be_external_service_latency_count{env=~\"$env\", is_error=\"1\"}[1m])) by(external_service, command)",
       "legendFormat": "{{external_service}} - {{command}}"
      }
     ]
    },
    {
     "title": "Provided API Error Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(id_game_.*#service_name#.*_be_provided_api_error{env=~\"$env\", type=\"0\"}[1m])) by(source)",
       "legendFormat": "Bad Request - {{source}}"
      },
      {
       "expr": "sum(increase(id_game_.*#service_name#.*_be_provided_api_error{env=~\"$env\", type=\"1\"}[1m])) by(source)",
       "legendFormat": "Internal Error - {{source}}"
      }
     ]
    },
    {
     "title": "CCU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "sum(increase(id_game_.*#service_name#.*_be_ccu{env=~\"$env\", cid=~\"$cid\"}[5s]))",
       "legendFormat": "Concurrent User"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic Monitoring Loadtest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Request Count [1m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "sum(increase(idgame_handled_total{service=~\".*#service_name#.*\",env=~\"$env\", cid=~\"$cid\", tenant=~\"$tenant\", path!~\".*ping.*\", region=\"xx\"}[1m])) by(path, method)",
       "legendFormat": "{{path}}-{{method}}"
      }
     ]
    },
    {
     "title": "HTTP latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(increase(idgame_handled_seconds_sum{service=~\".*#service_name#.*\",env=~\"$env\", tenant=~\"$cid\", path!~\".*ping.*\", region=\"xx\"}[1m]))by(path, method)/sum(increase(idgame_handled_seconds_count{service=~\".*#service_name#.*\",env=~\"$env\", tenant=~\"$cid\", path!~\".*ping.*\", region=\"xx\"}[1m]))by(path, method)",
       "legendFormat": "{{path}}-{{method}}"
      }
     ]
    },
    {
     "title": "HTTP Status Code [1M]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "sum(increase(idgame_handled_total{service=~\".*#service_name#.*\",env=~\"$env\", cid=~\"$cid\", tenant=~\"$tenant\", status_code!~\"200\", path!~\".*ping.*\", region=\"xx\"}[1m])) by(path, method, status_code)",
       "legendFormat": "{{path}}-{{method}}-{{status_code}}"
      }
     ]
    },
    {
     "title": "HTTP latency Pxx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(increase(idgame_handled_seconds_bucket{service=~\".*#service_name#.*\",env=~\"$env\", tenant=~\"$cid\", path!~\".*ping.*\", region=\"xx\"}[1m])) by (le, path, method))",
       "legendFormat": "p95: {{path}}-{{method}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum(increase(idgame_handled_seconds_bucket{service=~\".*#service_name#.*\",env=~\"$env\", tenant=~\"$cid\", path!~\".*ping.*\", region=\"xx\"}[1m])) by (le, path, method))",
       "legendFormat": "p75: {{path}}-{{method}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(increase(idgame_handled_seconds_bucket{service=~\".*#service_name#.*\",env=~\"$env\", tenant=~\"$cid\", path!~\".*ping.*\", region=\"xx\"}[1m])) by (le, path, method))",
       "legendFormat": "p50: {{path}}-{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Monitoring Loadtest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(rate(container_cpu_usage_seconds_total{pod=~\".*#service_name#.*\", image!~\".*pause.*\", pod=~\".*-xx.*\"}[60s]) / max(kube_pod_container_resource_limits_cpu_cores{pod=~\".*#service_name#.*\", pod=~\".*-xx.*\"}) * 100)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(pod:pod_memory_usage:rate{pod_name=~\".*#service_name#.*\", pod_name=~\".*-xx.*\"} / (pod:pod_memory_limit_bytes{pod_name=~\".*#service_name#.*\", pod_name=~\".*-xx.*\"} / 1024 / 1024 / 1024)) * 100",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Pod Restart Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(kube_pod_container_status_restarts_total{pod=~\".*#service_name#.*\", pod=~\".*-xx.*\"}[5m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Pod Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "kube_pod_status_ready{pod=~\".*#service_name#.*\", condition=\"true\", pod=~\".*-xx.*\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}